# Generated by Django 4.1.7 on 2023-03-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('manufacturer', models.TextField(blank=True, null=True)),
                ('scheme', models.TextField(blank=True, null=True)),
                ('assurance_level', models.TextField(blank=True, null=True)),
                ('protection_profile_s_field', models.TextField(blank=True, db_column='protection_profile(s)', null=True)),
                ('certification_date', models.TextField(blank=True, null=True)),
                ('archived_date', models.TextField(blank=True, null=True)),
                ('certification_report_url', models.TextField(blank=True, db_column='certification_report _URL', null=True)),
                ('security_target_url', models.TextField(blank=True, db_column='security_target-URL', null=True)),
                ('maintenance_date', models.TextField(blank=True, null=True)),
                ('maintenance_title', models.TextField(blank=True, null=True)),
                ('maintenance_report', models.TextField(blank=True, null=True)),
                ('maintenance_st', models.TextField(blank=True, db_column='maintenance_ST', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItSecChina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, db_column='company', max_length=45, null=True)),
                ('product', models.CharField(blank=True, db_column='product', max_length=45, null=True)),
                ('certification', models.CharField(blank=True, db_column='certification', max_length=45, null=True)),
                ('level', models.CharField(blank=True, db_column='level', max_length=45, null=True)),
                ('issue_date', models.CharField(blank=True, db_column='issue_date', max_length=45, null=True)),
                ('validation', models.CharField(blank=True, db_column='validation', max_length=45, null=True)),
                ('remark', models.CharField(blank=True, db_column='remark', max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Niap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(blank=True, null=True)),
                ('vid', models.CharField(blank=True, max_length=45, null=True)),
                ('conformance_claim', models.CharField(blank=True, max_length=200, null=True)),
                ('cctl', models.CharField(blank=True, max_length=80, null=True)),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('assurance_maintenance_date', models.DateField(blank=True, null=True)),
                ('scheme', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
